trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

stages:
# === Stage 1: Validate ===
- stage: validate
  jobs:
  - job: validate
    continueOnError: false
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'new-2025-ser-con'
        backendAzureRmResourceGroupName: 'backendstg-rg'
        backendAzureRmStorageAccountName: 'backendstgtf76587'
        backendAzureRmContainerName: 'tfstate'
        backendazureRmKey: 'deploy.terraform.tfstate'
        workingDirectory: '2-Deploy-StorageAccount-Terraform-AzurePipeline'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Validate'
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '2-Deploy-StorageAccount-Terraform-AzurePipeline'

# === Stage 2: Destroy ===
- stage: Destroy
  jobs:
  - job: destroy
    continueOnError: false
    steps:
    - checkout: self

    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Init'
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'new-2025-ser-con'
        backendAzureRmResourceGroupName: 'backendstg-rg'
        backendAzureRmStorageAccountName: 'backendstgtf76587'
        backendAzureRmContainerName: 'tfstate'
        backendazureRmKey: 'deploy.terraform.tfstate'
        workingDirectory: '2-Deploy-StorageAccount-Terraform-AzurePipeline'

    - task: TerraformTaskV3@3
      displayName: 'Terraform Destroy'
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        environmentServiceNameAzureRM: 'new-2025-ser-con'
        backendServiceArm: 'new-2025-ser-con'
        backendAzureRmResourceGroupName: 'backendstg-rg'
        backendAzureRmStorageAccountName: 'backendstgtf76587'
        backendAzureRmContainerName: 'tfstate'
        backendazureRmKey: 'deploy.terraform.tfstate'
        workingDirectory: '2-Deploy-StorageAccount-Terraform-AzurePipeline'
        args: '-auto-approve'
