trigger: none  # Disable CI trigger; use 'main' or your branch name to enable CI
pr: none  # Disable PR trigger; use 'main' or your branch name to enable PR validation
  # branches:
  #   include:
  #     - main   # or your branch name

pool:
  vmImage: 'ubuntu-latest'  # or your custom agent pool

stages:
- stage: validate
  jobs:
  - job: validate
    continueOnError: false
    steps:
    - task: TerraformInstaller@0
      displayName: 'Install Terraform'
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTaskV3@3
      displayName: init
      inputs:
        provider: 'azurerm'
        command: 'init'
        backendServiceArm: 'new-2025-ser-con'
        backendAzureRmResourceGroupName: 'backendstg-rg'
        backendAzureRmStorageAccountName: 'backendstgtf76587'
        backendAzureRmContainerName: 'tfstate'
        backendazureRmKey: 'deploy.terraform.tfstate'

    - task: TerraformTaskV3@3
      displayName: validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
        # backendServiceArm: 'azure-spn'
        # backendAzureRmResourceGroupName: 'terraform-rg'
        # backendAzureRmStorageAccountName: 'sktfaccount'
        # backendAzureRmContainerName: 'sktcontainername'
        # backendazureRmKey: 'terraform.tfstate'
        
      
- stage: deploy
  jobs:
  - deployment: deploy_storage_account
    displayName: 'Deploy Storage Account'
    continueOnError: false
    environment: 'dev'
    strategy:
     runOnce:
       deploy:
        steps: 
          - checkout: self

          - task: TerraformInstaller@0
            displayName: 'Install Terraform'
            inputs:
              terraformVersion: 'latest'
              

          - task: TerraformTaskV3@3
            displayName: 'Terraform Init'
            inputs:
              provider: 'azurerm'
              command: 'init'
              environmentServiceNameAzureRM: 'new-2025-ser-con'
              backendServiceArm: 'new-2025-ser-con'
              backendAzureRmResourceGroupName: 'backendstg-rg'
              backendAzureRmStorageAccountName: 'backendstgtf76587'
              backendAzureRmContainerName: 'tfstate'
              backendazureRmKey: 'deploy.terraform.tfstate'
              workingDirectory: 'terraform' 

          - task: TerraformTaskV3@3
            displayName: 'Terraform Plan'
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'new-2025-ser-con'
              backendServiceArm: 'new-2025-ser-con'
              backendAzureRmResourceGroupName: 'backendstg-rg'
              backendAzureRmStorageAccountName: 'backendstgtf76587'
              backendAzureRmContainerName: 'tfstate'
              backendazureRmKey: 'deploy.terraform.tfstate'
              workingDirectory: 'terraform'  

          - task: TerraformTaskV3@3
            displayName: 'Terraform Apply'
            inputs:
              provider: 'azurerm'
              command: 'apply'
              environmentServiceNameAzureRM: 'new-2025-ser-con'
              workingDirectory: 'storage' 
              # Optional: Set to true for auto-approve
              # args: '-auto-approve'